# Background and motivation

Many data system(for data ware housing,statistical computing) have developed specialized approaches for representing data with repeated value for more efficient storage and computation.

In [2]:
import numpy as np
import pandas as pd
value=pd.Series(['apple','orange','apple','apple']*2)
value

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [3]:
value.unique()

array(['apple', 'orange'], dtype=object)

In [4]:
value.value_counts()

apple     6
orange    2
dtype: int64

In [5]:
val =pd.Series([1,0,0,0,1]*2)
val

0    1
1    0
2    0
3    0
4    1
5    1
6    0
7    0
8    0
9    1
dtype: int64

In [6]:
dim=pd.Series(['apple','orange'])
dim

0     apple
1    orange
dtype: object

In [7]:
dim.take(val)
#this representation as integer is called as the categorical and  dictionary encoded representation

1    orange
0     apple
0     apple
0     apple
1    orange
1    orange
0     apple
0     apple
0     apple
1    orange
dtype: object

# Categorical Type In Pandas

In [32]:
fruit=['apple','orange','apple','apple','orange']*2
N=len(fruit)
df=pd.DataFrame({'fruit':fruit,'basket_id':np.arange(N),'count':np.random.randint(3,15,size=N),\
                'weight':np.random.uniform(0,4,size=N)},columns=['basket_id','fruit','count','weight'])

In [23]:
N

10

In [33]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4    orange
5     apple
6    orange
7     apple
8     apple
9    orange
Name: fruit, dtype: object

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
df

basket_id   fruit  count    weight
0          0   apple      8  0.035780
1          1  orange      8  0.773600
2          2   apple      5  3.425815
3          3   apple      6  2.906331
4          4  orange      8  1.843942
5          5   apple     14  1.589896
6          6  orange      8  2.760452
7          7   apple      4  3.141350
8          8   apple      3  2.542083
9          9  orange     10  1.401403

In [36]:
df['fruit']=df['fruit'].astype('category')

In [37]:
df

basket_id   fruit  count    weight
0          0   apple      8  0.035780
1          1  orange      8  0.773600
2          2   apple      5  3.425815
3          3   apple      6  2.906331
4          4  orange      8  1.843942
5          5   apple     14  1.589896
6          6  orange      8  2.760452
7          7   apple      4  3.141350
8          8   apple      3  2.542083
9          9  orange     10  1.401403

In [38]:
#you can see the datatype of the df.fruit
#it is now the category
df.fruit

0     apple
1    orange
2     apple
3     apple
4    orange
5     apple
6    orange
7     apple
8     apple
9    orange
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [44]:
c=df.fruit.values
c

[apple, orange, apple, apple, orange, apple, orange, apple, apple, orange]
Categories (2, object): [apple, orange]

In [51]:
# to see the categories of the df.fruit
category=c.categories
category

Index(['apple', 'orange'], dtype='object')

In [50]:
#to see the categories code of the df.fruit
code=c.codes
code

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1], dtype=int8)

In [54]:
#you can combine code and category
cats=pd.Categorical.from_codes(code,category)
cats

[apple, orange, apple, apple, orange, apple, orange, apple, apple, orange]
Categories (2, object): [apple, orange]

In [57]:
my_categories=pd.Categorical(['foo','bar','baz','foo','bar'])
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [58]:
my_categories.codes

array([2, 0, 1, 2, 0], dtype=int8)

In [59]:
my_categories.categories

Index(['bar', 'baz', 'foo'], dtype='object')

In [60]:
len(my_categories)

5

In [61]:
df1=pd.DataFrame({'key':my_categories,'data':np.arange(len(my_categories))})
df1

key  data
0  foo     0
1  bar     1
2  baz     2
3  foo     3
4  bar     4

In [62]:
df1.key

0    foo
1    bar
2    baz
3    foo
4    bar
Name: key, dtype: category
Categories (3, object): [bar, baz, foo]

In [66]:
ct=df1.key.values.categories
ct

Index(['bar', 'baz', 'foo'], dtype='object')

In [67]:
co=df1.key.values.codes
co

array([2, 0, 1, 2, 0], dtype=int8)

In [69]:
catg=pd.Categorical.from_codes(co,ct)
catg

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [71]:
#unless explicitly specified,categorical convertion assume no specific order of the categories.you can specify them with meaning full order by ordered=True
categ=pd.Categorical.from_codes(co,ct,ordered=True)
categ

[foo, bar, baz, foo, bar]
Categories (3, object): [bar < baz < foo]

In [73]:
# an unordered categorical instance can be converted as the specific order by as_ordered()
cats.as_ordered()

[apple, orange, apple, apple, orange, apple, orange, apple, apple, orange]
Categories (2, object): [apple < orange]

# Computation with Categorical

In [74]:
np.random.seed(12345)

In [78]:
draws=np.random.randn(1000)

In [81]:
bins=pd.qcut(draws,4)
bins

[(-0.0173, 0.703], (-3.55, -0.63], (0.703, 3.367], (-3.55, -0.63], (-0.63, -0.0173], ..., (-0.63, -0.0173], (-0.0173, 0.703], (-0.0173, 0.703], (0.703, 3.367], (0.703, 3.367]]
Length: 1000
Categories (4, interval[float64]): [(-3.55, -0.63] < (-0.63, -0.0173] < (-0.0173, 0.703] < (0.703, 3.367]]

In [82]:
bins.value_counts()

(-3.55, -0.63]      250
(-0.63, -0.0173]    250
(-0.0173, 0.703]    250
(0.703, 3.367]      250
dtype: int64

In [84]:
bins=pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

[Q3, Q1, Q4, Q1, Q2, ..., Q2, Q3, Q3, Q4, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [85]:
bins.value_counts()

Q1    250
Q2    250
Q3    250
Q4    250
dtype: int64

In [88]:
df.groupby('fruit').mean()

basket_id     count    weight
fruit                                
apple    4.166667  6.666667  2.273542
orange   5.000000  8.500000  1.694849

In [89]:
bins=pd.Series(bins,name='quartile')

In [90]:
bins

0      Q3
1      Q1
2      Q4
3      Q1
4      Q2
       ..
995    Q2
996    Q3
997    Q3
998    Q4
999    Q4
Name: quartile, Length: 1000, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [93]:
result=(pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())
result

quartile  count       min       max
0       Q1    250 -3.548824 -0.630470
1       Q2    250 -0.630465 -0.017749
2       Q3    250 -0.016887  0.702206
3       Q4    250  0.704870  3.366626

In [94]:
results=(pd.Series(draws).groupby(bins).agg(['count','min','max']))
results

count       min       max
quartile                           
Q1          250 -3.548824 -0.630470
Q2          250 -0.630465 -0.017749
Q3          250 -0.016887  0.702206
Q4          250  0.704870  3.366626

In [95]:
result['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [98]:
1000000//4

250000

# Better performance with categorical

In [100]:
N=10000000
labels=pd.Series(['foo','bar','baz','qux']*(N//4))

In [102]:
categories=labels.astype('category')

In [103]:
categories.memory_usage()

10000320

In [104]:
#you can see that labels consume significantly more memory than categories
labels.memory_usage()

80000128

In [106]:
#the conversion to categories is not free of course it is time cost
%time _=labels.astype('category')

Wall time: 622 ms


# Categorical Method

In [4]:
import pandas as pd
s=pd.Series(['a','b','c','d']*2)
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [5]:
cat_s=s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [6]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [7]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
cat_s2=cat_s.cat.set_categories(['a','b','c','d','e'])
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [9]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [10]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In large dataset categorical often use for better performance and for memory saving. After you filter a large dataset or series ,many category may not apear inthe dataset we get rid of thiswe can use remove-unuse-categories method method to trim  the unobserved categories

In [11]:

#'a','b' occur in (0th index,4th index) and(1st,5th index) respectively
cat_s3=cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [12]:
cat_s4=cat_s[cat_s.isin(['a', 'b','c','d','e'])]
cat_s4

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [13]:
cat_s4.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [14]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [15]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

# Creating dummy variable for modelling

when you are using statisiic or machine learning tool you often transfrom categorical data into dummy variable this is also known as one hot coading.this involve creating new column for each distinct category.thease coloumn contain 1s for occurance of each distinct categorical variable

In [16]:
cats=pd.Series(['a','b','c','d']*2)
cats

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [18]:
pd.get_dummies(cats)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

# Avanced groupby use
# Group transform and  'unrapped' groupby 

In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame({'keys':['a','b','c']*4,'value':np.arange(12.0)})
df

keys  value
0     a    0.0
1     b    1.0
2     c    2.0
3     a    3.0
4     b    4.0
5     c    5.0
6     a    6.0
7     b    7.0
8     c    8.0
9     a    9.0
10    b   10.0
11    c   11.0

In [2]:
df.groupby('keys').mean()

value
keys       
a       4.5
b       5.5
c       6.5

In [3]:
g=df.groupby('keys').value

In [4]:
g.mean()

keys
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [5]:
df.groupby('keys').apply(lambda x:x.mean())

value
keys       
a       4.5
b       5.5
c       6.5

In [6]:
df.groupby('keys').transform(lambda x: x.mean())

value
0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5

In [7]:
df.groupby('keys').value.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [8]:
df.groupby('keys').transform('mean')

value
0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5

In [9]:
df.transform(lambda x:x*2)

keys  value
0    aa    0.0
1    bb    2.0
2    cc    4.0
3    aa    6.0
4    bb    8.0
5    cc   10.0
6    aa   12.0
7    bb   14.0
8    cc   16.0
9    aa   18.0
10   bb   20.0
11   cc   22.0

In [10]:
df.groupby('keys').transform(lambda x: x*2)

value
0     0.0
1     2.0
2     4.0
3     6.0
4     8.0
5    10.0
6    12.0
7    14.0
8    16.0
9    18.0
10   20.0
11   22.0

In [11]:
g=df.groupby('keys')

In [12]:
g.transform(lambda x:x.rank(ascending=False))

value
0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0

In [13]:
df.transform(lambda x:x.rank(ascending=False))

keys  value
0   10.5   12.0
1    6.5   11.0
2    2.5   10.0
3   10.5    9.0
4    6.5    8.0
5    2.5    7.0
6   10.5    6.0
7    6.5    5.0
8    2.5    4.0
9   10.5    3.0
10   6.5    2.0
11   2.5    1.0

In [14]:
df.transform(lambda x:x.rank(ascending=True))

keys  value
0    2.5    1.0
1    6.5    2.0
2   10.5    3.0
3    2.5    4.0
4    6.5    5.0
5   10.5    6.0
6    2.5    7.0
7    6.5    8.0
8   10.5    9.0
9    2.5   10.0
10   6.5   11.0
11  10.5   12.0

In [15]:
g.transform(lambda x:x.rank(ascending=True))

value
0     1.0
1     1.0
2     1.0
3     2.0
4     2.0
5     2.0
6     3.0
7     3.0
8     3.0
9     4.0
10    4.0
11    4.0

In [16]:
g.apply(lambda x: x)

keys  value
0     a    0.0
1     b    1.0
2     c    2.0
3     a    3.0
4     b    4.0
5     c    5.0
6     a    6.0
7     b    7.0
8     c    8.0
9     a    9.0
10    b   10.0
11    c   11.0

In [17]:
df

keys  value
0     a    0.0
1     b    1.0
2     c    2.0
3     a    3.0
4     b    4.0
5     c    5.0
6     a    6.0
7     b    7.0
8     c    8.0
9     a    9.0
10    b   10.0
11    c   11.0

two major difference between apply and transform

input:

    1.apply implicitly passes all the column for each group as a dataframe to the custom function--
    2.while transform passes each column for each group individually as a Series to the custom function

output:

    .the custom function passed to 'apply' can return a scaler ,or a Series or DataFrame(or Numpy array even list)
     .the custom function passed to transforrm must return a sequence (a one dimentional list or Series or array) the same   lenth as the group
    

In [18]:
def normalise(x):
    return (x-x.mean())/x.std()


In [19]:
g.apply(normalise)

value
0  -1.161895
1  -1.161895
2  -1.161895
3  -0.387298
4  -0.387298
5  -0.387298
6   0.387298
7   0.387298
8   0.387298
9   1.161895
10  1.161895
11  1.161895

In [20]:
# the output in normalise and in apply is same
g.transform(normalise)

value
0  -1.161895
1  -1.161895
2  -1.161895
3  -0.387298
4  -0.387298
5  -0.387298
6   0.387298
7   0.387298
8   0.387298
9   1.161895
10  1.161895
11  1.161895

In [21]:
def inspect(x):
    return (type(x))

In [22]:
g.apply(inspect)

keys
a    <class 'pandas.core.frame.DataFrame'>
b    <class 'pandas.core.frame.DataFrame'>
c    <class 'pandas.core.frame.DataFrame'>
dtype: object

In [23]:
g.transform(inspect)

value
0   <class 'pandas.core.series.Series'>
1   <class 'pandas.core.series.Series'>
2   <class 'pandas.core.series.Series'>
3   <class 'pandas.core.series.Series'>
4   <class 'pandas.core.series.Series'>
5   <class 'pandas.core.series.Series'>
6   <class 'pandas.core.series.Series'>
7   <class 'pandas.core.series.Series'>
8   <class 'pandas.core.series.Series'>
9   <class 'pandas.core.series.Series'>
10  <class 'pandas.core.series.Series'>
11  <class 'pandas.core.series.Series'>

    builtin aggregate function like 'mean' or 'sum' are much faster than the apply function.this also have "fast-past" when with transform.this allow us to compute so called unwrapped group operation

In [24]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')
normalized

0   1   2   3   4   5   6   7   8   9  10  11  value
0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
1  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
2  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
3  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
4  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
5  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
6  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
7  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
8  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
9  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
10 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN
11 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    NaN

In [25]:
normalized = (df['value'] - g.value.transform('mean')) / g.value.transform('std')
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [26]:
type(df['value'])

pandas.core.series.Series

In [27]:
type(g.transform('mean'))

pandas.core.frame.DataFrame

In [28]:
type(g.value.transform('mean'))

pandas.core.series.Series

# Grouped time resampling

In [52]:
N=15
time=pd.date_range('2017/5/20',freq='1min',periods=N)
df=pd.DataFrame({'time':time,'value':np.arange(N)})
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [53]:
df1.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [54]:
time

DatetimeIndex(['2017-05-20 00:00:00', '2017-05-20 00:01:00',
               '2017-05-20 00:02:00', '2017-05-20 00:03:00',
               '2017-05-20 00:04:00', '2017-05-20 00:05:00',
               '2017-05-20 00:06:00', '2017-05-20 00:07:00',
               '2017-05-20 00:08:00', '2017-05-20 00:09:00',
               '2017-05-20 00:10:00', '2017-05-20 00:11:00',
               '2017-05-20 00:12:00', '2017-05-20 00:13:00',
               '2017-05-20 00:14:00'],
              dtype='datetime64[ns]', freq='T')

In [55]:
time.repeat(3)

DatetimeIndex(['2017-05-20 00:00:00', '2017-05-20 00:00:00',
               '2017-05-20 00:00:00', '2017-05-20 00:01:00',
               '2017-05-20 00:01:00', '2017-05-20 00:01:00',
               '2017-05-20 00:02:00', '2017-05-20 00:02:00',
               '2017-05-20 00:02:00', '2017-05-20 00:03:00',
               '2017-05-20 00:03:00', '2017-05-20 00:03:00',
               '2017-05-20 00:04:00', '2017-05-20 00:04:00',
               '2017-05-20 00:04:00', '2017-05-20 00:05:00',
               '2017-05-20 00:05:00', '2017-05-20 00:05:00',
               '2017-05-20 00:06:00', '2017-05-20 00:06:00',
               '2017-05-20 00:06:00', '2017-05-20 00:07:00',
               '2017-05-20 00:07:00', '2017-05-20 00:07:00',
               '2017-05-20 00:08:00', '2017-05-20 00:08:00',
               '2017-05-20 00:08:00', '2017-05-20 00:09:00',
               '2017-05-20 00:09:00', '2017-05-20 00:09:00',
               '2017-05-20 00:10:00', '2017-05-20 00:10:00',
               '2017-05-

In [56]:
np.tile(['a','b','c'],3)

array(['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c'], dtype='<U1')

In [57]:
df2=pd.DataFrame({'time':time.repeat(3),'key':np.tile(['a','b','c'],N),'value':np.arange(N*3.)})
df2

time key  value
0  2017-05-20 00:00:00   a    0.0
1  2017-05-20 00:00:00   b    1.0
2  2017-05-20 00:00:00   c    2.0
3  2017-05-20 00:01:00   a    3.0
4  2017-05-20 00:01:00   b    4.0
5  2017-05-20 00:01:00   c    5.0
6  2017-05-20 00:02:00   a    6.0
7  2017-05-20 00:02:00   b    7.0
8  2017-05-20 00:02:00   c    8.0
9  2017-05-20 00:03:00   a    9.0
10 2017-05-20 00:03:00   b   10.0
11 2017-05-20 00:03:00   c   11.0
12 2017-05-20 00:04:00   a   12.0
13 2017-05-20 00:04:00   b   13.0
14 2017-05-20 00:04:00   c   14.0
15 2017-05-20 00:05:00   a   15.0
16 2017-05-20 00:05:00   b   16.0
17 2017-05-20 00:05:00   c   17.0
18 2017-05-20 00:06:00   a   18.0
19 2017-05-20 00:06:00   b   19.0
20 2017-05-20 00:06:00   c   20.0
21 2017-05-20 00:07:00   a   21.0
22 2017-05-20 00:07:00   b   22.0
23 2017-05-20 00:07:00   c   23.0
24 2017-05-20 00:08:00   a   24.0
25 2017-05-20 00:08:00   b   25.0
26 2017-05-20 00:08:00   c   26.0
27 2017-05-20 00:09:00   a   27.0
28 2017-05-20 00:09:00   b   28.0
29 2017-05-20 00:09:00   c   29.0
30 2017-05-20 00:10:00   a   30.0
31 2017-05-20 00:10:00   b   31.0
32 2017-05-20 00:10:00   c   32.0
33 2017-05-20 00:11:00   a   33.0
34 2017-05-20 00:11:00   b   34.0
35 2017-05-20 00:11:00   c   35.0
36 2017-05-20 00:12:00   a   36.0
37 2017-05-20 00:12:00   b   37.0
38 2017-05-20 00:12:00   c   38.0
39 2017-05-20 00:13:00   a   39.0
40 2017-05-20 00:13:00   b   40.0
41 2017-05-20 00:13:00   c   41.0
42 2017-05-20 00:14:00   a   42.0
43 2017-05-20 00:14:00   b   43.0
44 2017-05-20 00:14:00   c   44.0

In [58]:
df2.set_index('time').groupby('key').resample('5min').sum()

value
key time                      
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [59]:
time_key = pd.Grouper(freq='5min')
resampled=(df2.set_index('time').groupby(['key',time_key]).sum())
resampled

value
key time                      
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [60]:
resampled.reset_index()

key                time  value
0   a 2017-05-20 00:00:00   30.0
1   a 2017-05-20 00:05:00  105.0
2   a 2017-05-20 00:10:00  180.0
3   b 2017-05-20 00:00:00   35.0
4   b 2017-05-20 00:05:00  110.0
5   b 2017-05-20 00:10:00  185.0
6   c 2017-05-20 00:00:00   40.0
7   c 2017-05-20 00:05:00  115.0
8   c 2017-05-20 00:10:00  190.0

In [64]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

In [65]:
le.fit(['yes','no','no','yes'])
p=le.transform(['yes','no','no','yes'])
p

array([1, 0, 0, 1], dtype=int64)

In [66]:
le.inverse_transform(p)

array(['yes', 'no', 'no', 'yes'], dtype='<U3')