# Handling Text

# Cleaning Text

In [1]:
text=["Interrobag. By Aishyarya Henritate",
     "Parking and Going. By Karl Guitter",
     "Today is the Night. By Jarek Ghosh"]

In [2]:
#strip Text
strip_text=[string.strip() for string in text]
#show the text without whitespace
strip_text

['Interrobag. By Aishyarya Henritate',
 'Parking and Going. By Karl Guitter',
 'Today is the Night. By Jarek Ghosh']

In [3]:
remove_periods=[string.replace('.','') for string in strip_text]
remove_periods

['Interrobag By Aishyarya Henritate',
 'Parking and Going By Karl Guitter',
 'Today is the Night By Jarek Ghosh']

In [4]:
#function for capitilize
def capitilizer(string):
    return string.upper()

In [5]:
capitilize_text=[capitilizer(string) for string in remove_periods]
capitilize_text

['INTERROBAG BY AISHYARYA HENRITATE',
 'PARKING AND GOING BY KARL GUITTER',
 'TODAY IS THE NIGHT BY JAREK GHOSH']

In [6]:
import re

In [7]:
def replace_letter_with_X(string:str) ->str:
    return re.sub(r"[a-zA-Z]","X",string)

In [8]:
text_with_X=[replace_letter_with_X(string) for string in capitilize_text]
text_with_X

['XXXXXXXXXX XX XXXXXXXXX XXXXXXXXX',
 'XXXXXXX XXX XXXXX XX XXXX XXXXXXX',
 'XXXXX XX XXX XXXXX XX XXXXX XXXXX']

# Parsing and  cleaning HTML

In [9]:
from bs4 import BeautifulSoup

In [10]:
html="""<div class='full_name'><span style='font-weight:bold'>Masego</span> Azra</div>"""

In [11]:
soup=BeautifulSoup(html,'lxml')

In [12]:
print(soup.prettify())

<html>
 <body>
  <div class="full_name">
   <span style="font-weight:bold">
    Masego
   </span>
   Azra
  </div>
 </body>
</html>


In [13]:
print(soup.div)

<div class="full_name"><span style="font-weight:bold">Masego</span> Azra</div>


In [14]:
soup.find('div')

<div class="full_name"><span style="font-weight:bold">Masego</span> Azra</div>

In [15]:
soup.find('div')['class']

['full_name']

In [16]:
#find the div with class name,show text
soup.find('div').get_text()

'Masego Azra'

In [17]:
#alternatively we can also do this code like this
soup.find('div',{'class':'full_name'}).text

'Masego Azra'

In [18]:
import unicodedata
import sys

In [52]:
unicodedata.category(chr(1))

'Cc'

In [19]:
sys.maxunicode

1114111

In [36]:
chr(1)

'\x01'

FromKeys: Create a new dictionary with keys from iterable and values set to value

In [54]:
#create text
text_data=['Hi!!! I. Love. This. Song...','10000% Agree !!! #LoveIT...','Right ?!?!']
#create punctuation dict
punctuation=dict.fromkeys(i for i in range (sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))

In [55]:
a=[string.translate(punctuation) for string in text_data]
a

['Hi I Love This Song', '10000 Agree  LoveIT', 'Right ']

In [38]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self,

# Tokenizing Text:

    this punkt need to be download:
    from nltk import word_tokenize
    import nltk
    nltk.download()

In [1]:
from nltk import word_tokenize

In [3]:
string='shubhamay chand is good boy.'
tokenize_word=word_tokenize(string)
tokenize_word

['shubhamay', 'chand', 'is', 'good', 'boy', '.']

In [4]:
from nltk import sent_tokenize

In [5]:
string='shubhamay chand is good boy. He want to enhance his career as a data scientist.'
sent_tokenize(string)

['shubhamay chand is good boy.',
 'He want to enhance his career as a data scientist.']

# Removing stopwords:

import nltk
nltk.download()

In [11]:
from nltk.corpus import stopwords

In [12]:
Tokenized_word='i','am','going','to','school' ,'then','i','return','home','and','again','went','to','the','park'

In [19]:
stops_word=stopwords.words('english')
stops_word[:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [16]:
after_removing_stop_words=[word for word in Tokenized_word if word not in stops_word]

In [17]:
after_removing_stop_words

['going', 'school', 'return', 'home', 'went', 'park']

# Stemming Word:

    Stemming reduce a word to its stem by identifying and removing affix(eg.gerurds) while keeping the root meaning of the word.for example both 'tradition' and'traditional' have 'tradit' as their stem,indicating that while they are different word,they represent same general concept.By stemming the data we turn it into something readable but closer to the base meaning and thus more suitable for comprising accross the observation

In [25]:
tokenized_words=['i','eagerly','wait','to','end','the','COVID-19','emedemic','afterthat',
                'i','try','to','go','Benglore','and','take','a','course','on','data','science']

In [26]:
from nltk.stem.porter import PorterStemmer

In [27]:
porter=PorterStemmer()

In [28]:
[porter.stem(word) for word in tokenized_words]

['i',
 'eagerli',
 'wait',
 'to',
 'end',
 'the',
 'covid-19',
 'emedem',
 'afterthat',
 'i',
 'tri',
 'to',
 'go',
 'benglor',
 'and',
 'take',
 'a',
 'cours',
 'on',
 'data',
 'scienc']

# Tagging Part of speech

In [32]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [7]:
from nltk import pos_tag
from nltk import word_tokenize

In [8]:
text_data='chris love outdoor running'

In [9]:
text_tag=pos_tag(word_tokenize(text_data))

In [10]:
text_tag

[('chris', 'NN'), ('love', 'VB'), ('outdoor', 'NN'), ('running', 'VBG')]

In [11]:
#filter word
noun=[word for word ,tag in text_tag if tag in ['NN','NNP','NNS','NNPS']]

In [12]:
noun

['chris', 'outdoor']

In [13]:
tweets=['i am eating bartito for breakfast',
      'political science is amazing field',
      'kolkata is a great city']
tweet_tags=[]
for tweet in tweets:
    tweet_tag=pos_tag(word_tokenize(tweet))
    tweet_tags.append([tag for word,tag in tweet_tag])

In [14]:
tweet_tag

[('kolkata', 'NN'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('great', 'JJ'),
 ('city', 'NN')]

In [15]:
tweet_tags

[['NN', 'VBP', 'VBG', 'NN', 'IN', 'NN'],
 ['JJ', 'NN', 'VBZ', 'JJ', 'NN'],
 ['NN', 'VBZ', 'DT', 'JJ', 'NN']]

One hot encoding of the tweet tag

In [16]:
from sklearn.preprocessing import MultiLabelBinarizer

In [17]:
one_hot_encoding=MultiLabelBinarizer()

In [18]:
array_after_one_hot_encoding=one_hot_encoding.fit_transform(tweet_tags)

In [19]:
array_after_one_hot_encoding

array([[0, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 0, 1]])

In [20]:
one_hot_encoding.classes_

array(['DT', 'IN', 'JJ', 'NN', 'VBG', 'VBP', 'VBZ'], dtype=object)

In [57]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

    Brown Corpus:The Brown corpus was the first million word electronic corpus,created 1961 at brown university.We can corpus as a list of sentances(where each sentance is itself just a list of words). We can optionally specify particular categories or files to read.

In [1]:
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger

In [2]:
#get some text from brown corpus,broken into sentance
sentance=brown.tagged_sents(categories='news')

In [3]:
sentance

[[('The', 'AT'), ('Fulton', 'NP-TL'), ('County', 'NN-TL'), ('Grand', 'JJ-TL'), ('Jury', 'NN-TL'), ('said', 'VBD'), ('Friday', 'NR'), ('an', 'AT'), ('investigation', 'NN'), ('of', 'IN'), ("Atlanta's", 'NP$'), ('recent', 'JJ'), ('primary', 'NN'), ('election', 'NN'), ('produced', 'VBD'), ('``', '``'), ('no', 'AT'), ('evidence', 'NN'), ("''", "''"), ('that', 'CS'), ('any', 'DTI'), ('irregularities', 'NNS'), ('took', 'VBD'), ('place', 'NN'), ('.', '.')], [('The', 'AT'), ('jury', 'NN'), ('further', 'RBR'), ('said', 'VBD'), ('in', 'IN'), ('term-end', 'NN'), ('presentments', 'NNS'), ('that', 'CS'), ('the', 'AT'), ('City', 'NN-TL'), ('Executive', 'JJ-TL'), ('Committee', 'NN-TL'), (',', ','), ('which', 'WDT'), ('had', 'HVD'), ('over-all', 'JJ'), ('charge', 'NN'), ('of', 'IN'), ('the', 'AT'), ('election', 'NN'), (',', ','), ('``', '``'), ('deserves', 'VBZ'), ('the', 'AT'), ('praise', 'NN'), ('and', 'CC'), ('thanks', 'NNS'), ('of', 'IN'), ('the', 'AT'), ('City', 'NN-TL'), ('of', 'IN-TL'), ('Atlant

In [24]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [27]:
#how you can know about the tag
nltk.help.upenn_tagset('JJ')

JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...


In [4]:
#we divide 4000 sentance for train dataset and remaning 623 for test
train=sentance[:4000]
test=sentance[4000:]

    If ambiguity come in tagging,first we take into account first two word using trigram tagger,if two word not present,we 'back off' and take into account the previous one word using 'Bigram tagger',if that fail we look at the word itself using Unigram tagger

In [5]:
#create backoff tagger
unigram=UnigramTagger(train)
bigram=BigramTagger(train,backoff=unigram)
trigram=TrigramTagger(train,backoff=bigram)

In [64]:
#show accuracy
trigram.evaluate(test)

0.8174734002697437

# Encoding text as a bag of word:

In [29]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
text_data=np.array(['I Love Brazil.Brazil!',
                  'Argentina can beet Brazil.',
                  'I chears for Argentina!! Argentina!! Argentina!!'])

In [33]:
#create word of feature matrix
count=CountVectorizer()

In [34]:
bag_of_word=count.fit_transform(text_data)

In [35]:
bag_of_word

<3x7 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [38]:
p=bag_of_word.toarray()
p

array([[0, 0, 2, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 0, 0],
       [3, 0, 0, 0, 1, 1, 0]], dtype=int64)

In [39]:
c=count.get_feature_names()
c

['argentina', 'beet', 'brazil', 'can', 'chears', 'for', 'love']

In [41]:
import pandas as pd
df=pd.DataFrame(p,columns=c)
df

argentina  beet  brazil  can  chears  for  love
0          0     0       2    0       0    0     1
1          1     1       1    1       0    0     0
2          3     0       0    0       1    1     0

In [66]:
count_2_gram=CountVectorizer(ngram_range=(1,2),stop_words='english',vocabulary=['argentina'])

In [67]:
bag=count_2_gram.fit_transform(text_data)

In [68]:
bag

<3x1 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [69]:
bag.toarray()

array([[0],
       [1],
       [3]], dtype=int64)

In [70]:
count_3_gram=CountVectorizer(ngram_range=(1,2),stop_words='english',vocabulary=['brazil'])

In [71]:
bag1=count_3_gram.fit_transform(text_data)

In [74]:
bag1.toarray()

array([[2],
       [1],
       [0]], dtype=int64)

#  Review Sparse matrix:

In [42]:
a=np.array([[0,0,0,1,0],[0,1,0,0,0],[0,0,0,0,1]])
a

array([[0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1]])

In [49]:
from scipy import sparse
print(sparse.csr_matrix(a))

  (0, 3)	1
  (1, 1)	1
  (2, 4)	1


# Weighting Word Importance

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
Tfdf=TfidfVectorizer()

In [78]:
weighing=Tfdf.fit_transform(text_data)

In [85]:
a=weighing.toarray()
a

array([[0.        , 0.        , 0.83559154, 0.        , 0.        ,
        0.        , 0.54935123],
       [0.42804604, 0.5628291 , 0.42804604, 0.5628291 , 0.        ,
        0.        , 0.        ],
       [0.84996348, 0.        , 0.        , 0.        , 0.37253328,
        0.37253328, 0.        ]])

In [81]:
t=Tfdf.vocabulary_
t

{'love': 6,
 'brazil': 2,
 'argentina': 0,
 'can': 3,
 'beet': 1,
 'chears': 4,
 'for': 5}

In [82]:
#get feature name
c=Tfdf.get_feature_names()

In [83]:
c

['argentina', 'beet', 'brazil', 'can', 'chears', 'for', 'love']

Compare the freequency of the word in the document( a tweet, movie review,speech transcript,etc) with the freequency of the word in other document using term-freequency document freequency(tf-idf).scikit-learn make it easy with TfidfVectorizer.

    Term Frequency(TF)=(No. of representative words in sentence)/(No of words in sentance)

    IDF=log[(No.of sentence)/(No.of sentence containing words)]
    
    Output return matrix contain TF*IDF of perticular matrix

In [90]:
pd.DataFrame(a,columns=c,index=['sen1','sen2','sen3'])

argentina      beet    brazil       can    chears       for      love
sen1   0.000000  0.000000  0.835592  0.000000  0.000000  0.000000  0.549351
sen2   0.428046  0.562829  0.428046  0.562829  0.000000  0.000000  0.000000
sen3   0.849963  0.000000  0.000000  0.000000  0.372533  0.372533  0.000000