# Encoding Nominial Categoical Feature

In [1]:
#import libraries
import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

In [2]:
#import feature
feature=np.array([['New Delhi'],['Kolkata'],['Bengaluru'],['Ranchi'],['Hydrabad'],['Kolkata']])
feature

array([['New Delhi'],
       ['Kolkata'],
       ['Bengaluru'],
       ['Ranchi'],
       ['Hydrabad'],
       ['Kolkata']], dtype='<U9')

In [3]:
one_hot=LabelBinarizer()

In [4]:
One_hot_coding_using_sklearn=one_hot.fit_transform(feature)

In [5]:
#one_hot_coded_feature
One_hot_coding_using_sklearn

array([[0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [28]:
#one_hot_coded_class
h=one_hot.classes_
h

array(['Bengaluru', 'Hydrabad', 'Kolkata', 'New Delhi', 'Ranchi'],
      dtype='<U9')

In [29]:
#made dataframe with class
df1=pd.DataFrame(One_hot_coding_using_sklearn,columns=h)

In [30]:
#dataframe after encoding
df1

Bengaluru  Hydrabad  Kolkata  New Delhi  Ranchi
0          0         0        0          1       0
1          0         0        1          0       0
2          1         0        0          0       0
3          0         0        0          0       1
4          0         1        0          0       0
5          0         0        1          0       0

In [7]:
one_hot.inverse_transform(one_hot.fit_transform(feature))

array(['New Delhi', 'Kolkata', 'Bengaluru', 'Ranchi', 'Hydrabad',
       'Kolkata'], dtype='<U9')

In [14]:
#create dummy variable from the pandas library
import pandas as pd
df=pd.get_dummies(feature[:,0])#To make the data one_dimensional we use feature[:,0]

In [12]:
df

Bengaluru  Hydrabad  Kolkata  New Delhi  Ranchi
0          0         0        0          1       0
1          0         0        1          0       0
2          1         0        0          0       0
3          0         0        0          0       1
4          0         1        0          0       0
5          0         0        1          0       0

In [15]:
#multiclass one_hot_coding with sklearn
multiclass_feature=np.array([['florida','texas'],['ohio','california'],['New Jersy','florida'],['Delwar','florida'],['texas','alabama']])
multiclass_feature

array([['florida', 'texas'],
       ['ohio', 'california'],
       ['New Jersy', 'florida'],
       ['Delwar', 'florida'],
       ['texas', 'alabama']], dtype='<U10')

In [17]:
hot_coding=MultiLabelBinarizer()

In [18]:
hot_coded_feature=hot_coding.fit_transform(multiclass_feature)

In [19]:
hot_coded_feature

array([[0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1]])

In [31]:
hot=hot_coding.classes_
hot

array(['Delwar', 'New Jersy', 'alabama', 'california', 'florida', 'ohio',
       'texas'], dtype=object)

In [32]:
#multiclass hot coded dataframe hot coding
df2=pd.DataFrame(hot_coded_feature,columns=hot)
df2

Delwar  New Jersy  alabama  california  florida  ohio  texas
0       0          0        0           0        1     0      1
1       0          0        0           1        0     1      0
2       0          1        0           0        1     0      0
3       1          0        0           0        1     0      0
4       0          0        1           0        0     0      1

# Encoding Ordinal Categorical Feature

In [22]:
import pandas as pd
dataframe=pd.DataFrame({'score':['low','low','medium','medium','large']})
dataframe

score
0     low
1     low
2  medium
3  medium
4   large

In [23]:
#create_map
scale_map={'low':0,'medium':1,'large':2}
#replace feature with map
dataframe.replace(scale_map)

score
0      0
1      0
2      1
3      1
4      2

In [24]:
dataframe=pd.DataFrame({'score':['low','low','medium','high','medium','barely more than medium','high']})
dataframe

score
0                      low
1                      low
2                   medium
3                     high
4                   medium
5  barely more than medium
6                     high

In [25]:
scale_map={'low':1,'medium':2,'barely more than medium':3,'high':4}
dataframe.replace(scale_map)

score
0      1
1      1
2      2
3      4
4      2
5      3
6      4

In [26]:
#in above example we assume that the distance between low and medium & distance 
#between  medium and barely more than medium is same but certainly it is not true 
#so the best way to be concuous about the numerical value mapped to classes:
scale_map={'low':1,'medium':2,'barely more than medium':2.1,'high':3}
dataframe.replace(scale_map)

score
0    1.0
1    1.0
2    2.0
3    3.0
4    2.0
5    2.1
6    3.0

# Encoding Dictionaries of Features

In [33]:
dict_list=[{'Red':5,'Yellow':2,'Blue':5},{'Blue':4,'Yellow':2,'Green':2},{'Red':3,'Yellow':2},{'Red':1,'Yellow':1,'Blue':2,'Green':4}]
dict_list

[{'Red': 5, 'Yellow': 2, 'Blue': 5},
 {'Blue': 4, 'Yellow': 2, 'Green': 2},
 {'Red': 3, 'Yellow': 2},
 {'Red': 1, 'Yellow': 1, 'Blue': 2, 'Green': 4}]

In [34]:
from sklearn.feature_extraction import DictVectorizer

In [43]:
dictvectorization=DictVectorizer(sparse=False)
feature_dict_vector=dictvectorization.fit_transform(dict_list)
feature_dict_vector

array([[5., 0., 5., 2.],
       [4., 2., 0., 2.],
       [0., 0., 3., 2.],
       [2., 4., 1., 1.]])

In [36]:
dictvectorized=DictVectorizer(sparse=True)
dictvectorized.fit_transform(dict_list)

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [40]:
feature_names=dictvectorization.get_feature_names()
feature_names

['Blue', 'Green', 'Red', 'Yellow']

In [44]:
df2=pd.DataFrame(feature_dict_vector,columns=feature_names)

In [45]:
df2

Blue  Green  Red  Yellow
0   5.0    0.0  5.0     2.0
1   4.0    2.0  0.0     2.0
2   0.0    0.0  3.0     2.0
3   2.0    4.0  1.0     1.0

In [50]:
#create word dictionary
dict1={'Red':6,'Green':4}
dict2={'Yellow':5}
dict3={'Red':3,'Blue':5,'Green':6}
dict4={'Green':4,'Blue':2,'Red':3,'Yellow':4}
#creating a dict_list
dict_list=[dict1,dict2,dict3,dict4]
feature_transform=DictVectorizer(sparse=False)
feature_transformation=feature_transform.fit_transform(dict_list)

In [51]:
feature_transformation

array([[0., 4., 6., 0.],
       [0., 0., 0., 5.],
       [5., 6., 3., 0.],
       [2., 4., 3., 4.]])

In [55]:
df3=pd.DataFrame(feature_transformation,columns=feature_transform.get_feature_names())

In [56]:
df3

Blue  Green  Red  Yellow
0   0.0    4.0  6.0     0.0
1   0.0    0.0  0.0     5.0
2   5.0    6.0  3.0     0.0
3   2.0    4.0  3.0     4.0

In [60]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [62]:
#create categorical feature
X=np.array([[1,0.25,2.1],[0,0.56,2.2],[0,2.5,1.56],[1,2.1,1.56]])
X

array([[1.  , 0.25, 2.1 ],
       [0.  , 0.56, 2.2 ],
       [0.  , 2.5 , 1.56],
       [1.  , 2.1 , 1.56]])

In [64]:
X_with_nan=np.array([[np.nan,0.23,0.21],[np.nan,2.3,2.1],[np.nan,0.25,0.26]])
X_with_nan

array([[ nan, 0.23, 0.21],
       [ nan, 2.3 , 2.1 ],
       [ nan, 0.25, 0.26]])

In [65]:
clf=KNeighborsClassifier(3,weights='distance')

In [68]:
training_model=clf.fit(X[:,1:],X[:,0])

In [69]:
imputed_value=training_model.predict(X_with_nan[:,1:])

In [70]:
imputed_value

array([1., 0., 1.])

In [73]:
#join imputed value and X_with_nan[:,1:]
predicted=np.hstack((imputed_value.reshape(-1,1),X_with_nan[:,1:]))
predicted

array([[1.  , 0.23, 0.21],
       [0.  , 2.3 , 2.1 ],
       [1.  , 0.25, 0.26]])

In [76]:
#join join X and predicted
total_feature=np.vstack((X,predicted))
total_feature

array([[1.  , 0.25, 2.1 ],
       [0.  , 0.56, 2.2 ],
       [0.  , 2.5 , 1.56],
       [1.  , 2.1 , 1.56],
       [1.  , 0.23, 0.21],
       [0.  , 2.3 , 2.1 ],
       [1.  , 0.25, 0.26]])

In [83]:
total_feature_before_predicted=np.vstack((X,X_with_nan))
total_feature_before_predicted

array([[1.  , 0.25, 2.1 ],
       [0.  , 0.56, 2.2 ],
       [0.  , 2.5 , 1.56],
       [1.  , 2.1 , 1.56],
       [ nan, 0.23, 0.21],
       [ nan, 2.3 , 2.1 ],
       [ nan, 0.25, 0.26]])

In [86]:
# altenatively you can do in this way
from sklearn.impute import SimpleImputer
impute=SimpleImputer(strategy='most_frequent')
impute.fit_transform(total_feature_before_predicted)

array([[1.  , 0.25, 2.1 ],
       [0.  , 0.56, 2.2 ],
       [0.  , 2.5 , 1.56],
       [1.  , 2.1 , 1.56],
       [0.  , 0.23, 0.21],
       [0.  , 2.3 , 2.1 ],
       [0.  , 0.25, 0.26]])

# handling imbalanced dataset

Training a machine  learning model on an imbalanced dataset can introduce unique challege to the learning prblem.Imbalanced datatpically refers to a classification problem where the number observation per class is not equally distributed,often youwill have a large amount of data/observation for one class(referred to as the majority class) and much fewer observation for one or more other classes(reffered to as minority class).for example ,suppose you are building a classifier to classify a credit card transaction a fraudlant or authentic-you will likely have 10000 authentic transaction for every fraudlent transaction,thats quite an imbalance

In [37]:
from sklearn.datasets import load_iris

In [38]:
iris=load_iris()

In [39]:
feature=iris.data

In [40]:
feature[0:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [41]:
target=iris.target

In [42]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [43]:
target.size

150

In [44]:
#removefirst 40 observation
feature=feature[40:,:]
target=target[40:]

In [45]:
feature.shape

(110, 4)

In [46]:
target.shape

(110,)

In [47]:
target=np.where((target==0),0,1)

In [48]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Many algorithm in sckit learn offer a parameter to weight a class during training to counter act effectof ther imbalance

In [49]:
weights={0:0.9,1:0.1}

In [51]:
#weight in random forest written as class_weight={0:1,1:2}.it means class0 have weight of 1 and class1 have weight of 2 

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
# create a random forest classifier with weight to deal with imbalanced dataset
rf=RandomForestClassifier(class_weight=weights)

In [55]:
rf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight={0: 0.9, 1: 0.1}, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [56]:
#alternatively we can pass balanced,which automaticly create weights inversely proportional to the class frequency
rfs=RandomForestClassifier(class_weight='balanced')
rfs

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

To deal with imbalaced dataset,we can downsample the majority class and upsample the  minority class.In downsampling,we ramdomly sample without replacement from the majority class(i.e the class with major observation) to create a new subset of observation equal in size to the minority class.For example,if the minority class has 10 observation,we will randomly  select 10 observation from the majority class and use this total 20 observation with training dataset.

In upsamling we repetedly sample with replacement from the minority class to make it equal size as majority class.The decision between using downsampling and upsampling is context_specific in general we use both to see which give better result.

In [58]:
i_class0=np.where(target==0)[0]
i_class1=np.where(target==1)[0]

In [59]:
#no of observation in each class
n_class0=len(i_class0)
n_class1=len(i_class1)

In [60]:
n_class0

10

In [61]:
n_class1

100

In [62]:
i_class1_downsampled=np.random.choice(i_class1,size=n_class0,replace=False)

In [63]:
len(i_class1_downsampled)

10

In [66]:
#join together the class 0 target matrix with the class1 target  downsampled matrix 
np.hstack((target[i_class0],target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
#join together the class0 feature matrix and downsampled class1 feture matrix
np.vstack((feature[i_class0],feature[i_class1_downsampled]))

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [5.7, 2.5, 5. , 2. ],
       [4.9, 2.4, 3.3, 1. ],
       [6.5, 3. , 5.2, 2. ],
       [5.6, 2.7, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [6.8, 3. , 5.5, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [6.6, 2.9, 4.6, 1.3],
       [6.3, 2.3, 4.4, 1.3]])

In [68]:
import numpy as np
a=np.array([0,0,0,1,0,1,1,0,0,0,1,1,0,1])
np.where(a==0)[0]

array([ 0,  1,  2,  4,  7,  8,  9, 12], dtype=int64)

In [69]:
import numpy as np
a=np.array([0,0,0,1,0,1,1,0,0,0,1,1,0,1])
np.where(a==0)

(array([ 0,  1,  2,  4,  7,  8,  9, 12], dtype=int64),)