# Vectors,Matrices and Array

    #Creating a Vector

In [1]:
import numpy as np
#Create a vector as a row
vector_row=np.array([1,2,3])
vector_row

array([1, 2, 3])

#create a vecor as a column
vector_column=np.array([[1],[2],[3]])
vector_column

In [4]:
#create a matrix
matrix=np.array([[1,2],[1,2],[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

# Sparse Matrix

In [5]:
#above matrix contrix contain 3 rows and two columns
#but numpy has a sepatrix datastucture as matxix
#matrix object not recommened for two reason first array are defecto data structure of numpy array
#two,vast majority of numpy array return array not matrix
matrix_object=np.mat([[2,3],[2,3],[2,3]])
matrix_object

matrix([[2, 3],
        [2, 3],
        [2, 3]])

Creating a sparse matrix

    sparse matrix only store non-zero values assume that all the value is zero,leading to the significant computational saving

In [6]:
matrix=np.array([[0,0],[0,1],[3,0]])
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [9]:
#creating a sparse matrix
#create compressed spared row matrix
from scipy import sparse
sparse_matrix=sparse.csr_matrix(matrix)
print(sparse_matrix)
#in the above matrix one non_zero value is 1 whoose index is (1,1)
#another non-zero element is the 3 whose index is (2,0)

  (1, 1)	1
  (2, 0)	3


In [11]:
#the effacy of sparse matrix is more efficient in the large_matrix
large_matrix=np.array([[0,0,0,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0,0],[0,0,0,0,3,0,0,0,0,0,0]])
large_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0]])

In [13]:
large_sparse_matrix=sparse.csr_matrix(matrix)
print(large_sparse_matrix)

  (1, 1)	1
  (2, 0)	3


In [15]:
A=sparse.csr_matrix([[1,2,0],[0,0,3],[4,0,5]])
print(A)

  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5


In [20]:
v=np.array([1,0,-1])
v

array([ 1,  0, -1])

In [21]:
A.dot(v)

array([ 1, -3, -1], dtype=int32)

In [22]:
#same result obtained by
A=np.array([[1,2,0],[0,0,3],[4,0,5]])
v=np.array([1,0,-1])
A.dot(v)

array([ 1, -3, -1])

# Selecting a element

In [2]:
import numpy as np
#create a row vector
vector=np.array([1,2,3,4,5,6])
#selecting third element of vector
vector[2]

3

In [3]:
#create a matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
#selecting second ow and second column of the matrix
matrix[1,1]

5

In [4]:
#numpy array offer a wide variety of method for slicing and indexing
#selecting all element of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [6]:
#select everithing up to and including the third element
vector[:3]

array([1, 2, 3])

In [7]:
#selecting the last element
vector[-1]

6

In [9]:
#selecting the first two row and all column of the matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#select all row and the 2nd column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

# Describe a matrix 

In [12]:
a=np.array([[1,2,3,4],
           [7,8,9,5],
           [10,11,12,12]])

In [13]:
a.shape

(3, 4)

In [14]:
a.size

12

In [15]:
a.ndim

2

# Applying Operation to element

In [16]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Define a vectorized function which takes a nested sequence of object or numpy array as input and return a single numpy array or tuple of numpy array.The vectorized function evalute pyfunc over successive tuple of the input array like the python map function ,expect it use broadcasting rule of python

    numpy vectorized class convert a function  into a function that can apply to all the element in an array or slice of an array.It is worth nothing to mention here that vectorized is a essential for loop over the over the elementand does not increse the performance.Even more numpy array allow us to perform the operation even there is difference in the dimension(broadcasting)

In [23]:
#creating a function that add 100 to something
add_100=lambda i:i+100
# create vectorized add_function
vectorized_add_100=np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
#apply function in dataframe
import pandas as pd
a=pd.DataFrame({'a':[1,2,3,4]})
a

a
0  1
1  2
2  3
3  4

In [22]:
a.apply(add_100)

a
0  101
1  102
2  103
3  104

Simple broadcasting

In [24]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Finding a maximum and minimum values

In [28]:
import numpy as np
matrix=np.array([[1,2,3],[1,5,6],[2,3,4]])
#finding maximum value
np.max(matrix)

6

In [29]:
#finding minimumum values
np.min(matrix)

1

In [30]:
#finding maximum in each column
np.max(matrix,axis=0)

array([2, 5, 6])

In [31]:
#finding maximum in each column
np.max(matrix,axis=1)

array([3, 6, 4])

    *axis=0
    *simplest way to remember it as 0=down
    *use axis=0 to apply a method down to each column

    *axis=1
    *simplest way to remember it as =across
    *use axis  to apply a method across each row

In [32]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#adding array as per down the column
np.sum(a,axis=0)

array([5, 7, 9])

In [34]:
#adding a array as per across the array
np.sum(a,axis=1)

array([ 6, 15])

# Calculating Average,Variance and Standerd Deviation

In [35]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
#return mean
#(1+2+3+4+5+6+7+8+9)/6
np.mean(mat)

5.0

In [36]:
#compute variance
np.var(mat)

6.666666666666667

In [37]:
#return standerd matrix
np.std(matrix)

1.632993161855452

In [38]:
#just like max and min you can apply mean
np.mean(mat,axis=0)

array([4., 5., 6.])

# Reshaping a array

In [39]:
a=np.array([[1,2,3],[4,5,6],[6,7,8],[10,11,12]])

In [40]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [10, 11, 12]])

In [42]:
#reshape a array from two dimention two 3 dimension
a.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 6,  7],
        [ 8, 10],
        [11, 12]]])

In [43]:
#reshape the shape from two dimention to two dimention but change in shape
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 6,  7],
       [ 8, 10],
       [11, 12]])

In [44]:
#reshape(-1,1) mean one column as many as row
a.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 6],
       [ 7],
       [ 8],
       [10],
       [11],
       [12]])

In [45]:
#reshape(1,-1) means one row as many column
a.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  6,  7,  8, 10, 11, 12]])

In [46]:
#change in one dimention
a.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 10, 11, 12])

# Transposing a matrix  and vector

In [67]:
import numpy as np
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#transpose of a matrix
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
#transposing is common operation in linear algebra where row and column element swapped.One nuanced point that is typically overlooked from the linear algebra is that
#a vector cannot transposed vecause it is collection of values
#transpose of a vector
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [55]:
np.array([[1,2,3,4,5,6]])

array([[1, 2, 3, 4, 5, 6]])

In [56]:
#transpose a row vector
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flatten a matrix

In [58]:
mat1=np.array([[7,8,9],[5,6,7],[8,9,10]])
mat1

array([[ 7,  8,  9],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [59]:
mat1.flatten() #it is one dimentional

array([ 7,  8,  9,  5,  6,  7,  8,  9, 10])

In [60]:
#you cn covert it into the row-vector by reshape(1,-1)
matrix.reshape(1,-1)

array([[1, 2, 3, 1, 5, 6, 2, 3, 4]])

the rank of a matrix is defined as the (a)maximum number of linearly independent column vector in the matrix (b) or maximum number of the linearly independent row vector in the matrix

In [63]:
#to find rank of the matrix is esy thanks to matrix_rank
import numpy as np
a=np.array([[1,1,12],[1,1,10],[1,1,15]])
np.linalg.matrix_rank(a)

2

# Calculatin the determinant


In [65]:
b=np.array([[7,8,9],[5,4,7],[8,5,7]])
np.linalg.det(b)

55.99999999999997

In [68]:
np.linalg.det(mat)

-9.51619735392994e-16

# Getting the diagonal of a matrix

In [69]:
matr=np.array([[1,2,3],[4,5,6],[7,8,9]])
matr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
#getting the diagonal of a matrix
np.diagonal(matrix)

array([1, 5, 4])

In [71]:
#alternative way to find diagonal
matrix.diagonal()

array([1, 5, 4])

In [73]:
#return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [75]:
#treturn diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([1, 3])

# Trace of the matrix

In [76]:
#trace of the matrix is  the sum of a diagonal element often used to under hood of machine learning method
sum(matrix.diagonal())

10

In [78]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
m.trace()

15

# Eigenvalue and Eigenvector

The formula of the eigen value and eigenvector is A*v=lambda *v
{where v is eigen vector and lambda is the eigen value}

    we can transform and change matrices into new vectors by multiplying a matrix with a vetor.the multiplication of the matrix bu a new vector compute a new vector this is the transformed vector

      if the new transformed vector is just a scaled form of the original vector is known to be an eigen vector of the original matrix.Vector that have this  characterties are special vector and they are known as eigenvector .Eigenvector can be used to represent large dimentional matrix.
      what is an eigen value?
      ans: the scaler that is used to transform a eigenvector

In [2]:
import numpy as np
a=np.array([[-6,3],[4,5]])
a

array([[-6,  3],
       [ 4,  5]])

In [3]:
eigenvalues,eigenvectors=np.linalg.eig(a)

In [4]:
eigenvalues#here is two eigen values one is '-7' other is 6

array([-7.,  6.])

In [6]:
eigenvectors#here one eigen vector is[-9486833,0.31622777] and another is[-0.24253563,-.9701425]

array([[-0.9486833 , -0.24253563],
       [ 0.31622777, -0.9701425 ]])

In [10]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues,eigenvectors=np.linalg.eig(matrix)
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [11]:
eigenvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

# dot product

In [12]:
#create a vector
a=np.array([1,2,3])
#creating another vector
b=np.array([4,5,6])
#compute dot product
np.dot(a,b)

32

In [13]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [14]:
d=np.array([[5,6],[7,8]])
d

array([[5, 6],
       [7, 8]])

In [15]:
np.dot(c,d)#1*5+2*7=19,1*6+2*8=22

array([[19, 22],
       [43, 50]])

In [16]:
#you can also compute dot product as written below
a@b

32

In [17]:
#compute dot product of c and d matrix
c@d

array([[19, 22],
       [43, 50]])

# Adding and Substracting matrix

In [18]:
matrix_a=np.array([[1,2,3],[4,5,3],[7,8,5]])
matrix_b=np.array([[5,4,6],[2,5,4],[7,8,2]])
matrix_a

array([[1, 2, 3],
       [4, 5, 3],
       [7, 8, 5]])

In [19]:
matrix_b

array([[5, 4, 6],
       [2, 5, 4],
       [7, 8, 2]])

In [20]:
matrix_a+matrix_b

array([[ 6,  6,  9],
       [ 6, 10,  7],
       [14, 16,  7]])

In [21]:
matrix_a-matrix_b

array([[-4, -2, -3],
       [ 2,  0, -1],
       [ 0,  0,  3]])

In [22]:
#we can also compute substraction by following method
np.add(matrix_a,matrix_b)

array([[ 6,  6,  9],
       [ 6, 10,  7],
       [14, 16,  7]])

In [24]:
np.subtract(matrix_a,matrix_b)

array([[-4, -2, -3],
       [ 2,  0, -1],
       [ 0,  0,  3]])

# Multiplying matrices

In [25]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
mat1=np.array([[3,4,5],[2,3,4],[4,5,6]])
mat1

array([[3, 4, 5],
       [2, 3, 4],
       [4, 5, 6]])

In [27]:
np.dot(mat,mat1)

array([[ 19,  25,  31],
       [ 46,  61,  76],
       [ 73,  97, 121]])

In [28]:
#we can also compute dot product by doing below code
mat@mat1

array([[ 19,  25,  31],
       [ 46,  61,  76],
       [ 73,  97, 121]])

In [29]:
#we can compute element wise product by doing this
mat*mat1#1*3=8,2*4=8,3*5=15

array([[ 3,  8, 15],
       [ 8, 15, 24],
       [28, 40, 54]])

# Generating random variable

Seed function is used to save the state of a random number,so that it can generate on multiple execution of the code on the same machine or the different machine (for a specific seed value ).the seed value is the previous value number generated by the generator.for the first time when there is not ,it uses current system time

In [36]:
np.random.seed(0)

In [37]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [38]:
np.random.rand(3)

array([0.54488318, 0.4236548 , 0.64589411])

In [41]:
np.random.seed(0)
np.random.randn(3,3)

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [42]:
np.random.seed(0)
np.random.randn(3,3)#for the same seed value the generator generate same random number

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [45]:
#generate three integer between0 and 11 
np.random.randint(0,11,3)

array([6, 7, 7])

In [47]:
#draw three number from nirmal distribution with mean 0 and standerd deviation 1
np.random.normal(0,1,3)

array([ 0.4105985 , -2.42595457, -0.4530558 ])

the logistic distribution is a continious distribution functionn .both its pdf and cdf function have been used in many different  used in different area such as logistic regression,logit model,neural network now in modelling and finance .The logistic distribytion has larger tail than a normal distribution so it is more consistant with the underlying data and provide better insight into the likelihood of extreme event

The difference between normal and logistic distribytion lies in the tails and behaviour of failure rate.the logistic distribution has much longer tail than the normal distribution

the logistic distribution is used for modelling growth and also for logistic regression.It is symmetrical unimodel(it has one peak) and is similar in shape with normal distribution.In fact the logistic and normal distribution are so close in shape (although the logistic need more fatter tail than it) that for most application it is impossible to tell one from the other.
the logistic distribution is main ly used for the simple commulative formula to work with.finding cummulative probability in normal distribution required z-score .it is so difficult.the logistic distribution has much simpler cdf formula

In [1]:
import numpy as np
#draw three line from logistic distribution with mean 0 and scale 1
np.random.logistic(0,1,3)

array([ 0.2328984, -0.8981948,  0.3935762])

In [2]:
#draw three number greater than or equal to 1 but less than 2
np.random.uniform(1,2,3)

array([1.99538023, 1.04010986, 1.42163457])